services:
  hugo:
    container_name: blog_hugo
    build:
      args:
        HUGO_VERSION: 0.120.4
        GO_VERSION: 1.21.4
        NODE_VERSION: 18
      target: final-image
      tags:
        - "seb7/hugo:1.0.0"
    expose:
      - 1313
    ports:
      - target: 1313
        published: 1313
    volumes:
      - type: bind
        source: ./
        target: /home/app
    user: "0:1000"
    # pour ne pas afficher les "drafts" - faire un autre compose.yml ?
    # entrypoint: hugo serve --bind 0.0.0.0 -p 1313 1>/dev/null & hugo --watch
