baseURL = "https://blog.seb7.fr/"
#baseURL = "http://0.0.0.0:8000/"
#title = "SebSept Dev Blog"
#theme = "terminal"
#theme = "beautifulhugo-master"
theme = "fuji"

hasCJKLanguage = true
enableEmoji = true
enableRobotsTXT = true
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

## Change this two to switch between different language
languageCode = "fr-fr"           # For RSS, view https://www.rssboard.org/rss-language-codes
defaultContentLanguage = "fr" # For HTML page, now support: en, zh-hans, zh-hant, ja, nl, pl, it

[languages]
[languages.fr]
title = "SebSept Dev Blog"
subtitle = "Quelques notes de developeur php."
keywords = ""
copyright = ""
#menuMore = "Suite"
#readMore = "Suite..."
#readOtherPosts = "Autres notes"
#
#[languages.en.params.logo]
#logoText = "SebSept Dev Blog"
#logoHomeLink = "/"
#
#[languages.en.menu]
#[[languages.en.menu.main]]
#identifier = "a-propos"
#name = "A propos"
#url = "/a-propos"
#
#[[languages.en.menu.main]]
#identifier = "legal"
#name = "Mentions légales"
#url = "/legal"

summaryLength = 100 # Custom summary length, add <!--more--> in post file to custom split point
paginate = 30

# googleAnalytics = "UA-000000000-0" # Set your Google Analytics UA here

[outputFormats]
[outputFormats.SearchIndex]
isPlainText = true
notAlternative = true
mediaType = "application/json"
path = "/search/"

[outputs]
home = ["HTML", "RSS", "SearchIndex"]

[permalinks]
post = "/:slug/" # Custom post links, e.g. "/:year/:month/:title/"

[params]
author = "Sébastien Monterisi"                # You can also set author in post front matter individually
#subTitle = "Quelques notes de developeur php."
defaultTheme = "dark"              # default theme when first visit (auto|dark|light)

# Source URL of the website, will appear in the footer
#sourceURL = "https://github.com/dsrkafuu/hugo-theme-fuji"

# Use CloudFlare Workers to accelerate the Google Analytics
# If you are using this please comment the googleAnalytics above
# Check https://github.com/SukkaW/cloudflare-workers-async-google-analytics for more details
# googleAnalyticsTid = "UA-000000000-0"
# googleAnalyticsRoute = "https://*.*.workers.dev/"

# Google AdSense
# The AdSense code will be inserted between the head tags of your site.
# googleAdsense = "0000000000000000"

# Word counter and read time indicator in post metadata
showWordCounter = true
showReadTime = true

# License in the footer
showLicenseInFooter = true

# License at the end of each post
showLicense = false
showToc = false

# Copyright
copyrightStartYear = "2022"

# Open Graph & Twitter Card variables
# You can also set description and images in post front matter individually
description = "SebSept Dev Blog -Quelques informations sur mes aventures de developeur php."
og = "/img/og.png"                                          # This will use the image called og.png in static/img folder

# Posts shown in homepage
mainSections = ["post"]

# Bangumi image chart id
# bgmImageChart = "000000"

# License
license = "CC BY-NC-SA 4.0"
licenseLink = "http://creativecommons.org/licenses/by-nc-sa/4.0/"

# Comments
# utterances, see: https://utteranc.es/
# utterancesRepo = "*/*"
# utterancesIssueTerm = "pathname"

# Disqus, see: https://disqus.com/admin/install/platforms/universalcode/
# disqusShortname = "*********"
# Also use DisqusJS for accessing from Mainland China, see: https://github.com/SukkaW/DisqusJS
# If you want to set multiple api key, see theme's README for more details
# disqusJSApi = "https://*********/"
# disqusJSApikey = "**********"

# custom lazyload placeholder
# 16:9
lazyPlaceholder = "/assets/lazyload/dsrca_loading_480x270.svg"
# 32:9
lazyPlaceholderRow = "/assets/lazyload/dsrca_loading_960x270.svg"
# 8:9
lazyPlaceholderCol = "/assets/lazyload/dsrca_loading_480x540.svg"

# Let images display in full brightness under dark mode
# disableDarkImage = true

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true # Enable user to embed HTML snippets in Markdown content
[markup.highlight]
codeFences = false # Disable Hugo's code highlighter

[markup.tableOfContents]
startLevel = 2
endLevel = 3

[taxonomies]
tag = "tags"

[menu]
#[[menu.nav]]
#name = "Home"
#url = "/"
#weight = 1
#[[menu.nav]]
#name = "Archives"
#url = "/archives/"
#weight = 2
[[menu.nav]]
name = "Stack"
url = "/stack"
weight = 2
#[[menu.nav]]
#name = "A Propos"
#url = "/a-propos/"
#weight = 3
[[menu.nav]]
name = "Légal"
url = "/legal/"
weight = 4
[[menu.nav]]
name = "RSS"
url = "/index.xml"
weight = 5

[[menu.link]]
name = "GitHub"
url = "https://github.com/SebSept"
weight = 1
[[menu.link]]
name = "Twitter"
url = "https://twitter.com/seb_sept"
weight = 2
#[[menu.link]]
#name = "bilibili"
#url = "https://space.bilibili.com/19767474"
#weight = 3

[build]
noJSConfigInAssets = true

[security]
enableInlineShortcodes = true
